# Branch protection rules for main and development branches
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - validate
          - branch-naming
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null

  - name: development
    protection:
      required_status_checks:
        strict: true
        contexts:
          - validate
          - branch-naming
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null
