import { MedicalRecord } from "../types";

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: "1",
    patientId: "1",
    patientName: "Max",
    veterinarianId: "1",
    veterinarianName: "Dhr. Smit",
    type: "CONSULTATIE",
    date: "2024-03-20",
    status: "ACTIEF",
    diagnosis: "Reguliere controle",
    treatment: "Geen behandeling nodig",
    notes: "Patiënt is gezond",
    chiefComplaint: "Reguliere controle",
    createdAt: "2024-03-20T10:00:00Z",
    updatedAt: "2024-03-20T10:00:00Z",
  },
  {
    id: "2",
    patientId: "2",
    patientName: "Bella",
    veterinarianId: "2",
    veterinarianName: "Dhr. Jansen",
    type: "OPERATIE",
    date: "2024-03-21",
    status: "ACTIEF",
    diagnosis: "Sterilisatie operatie",
    treatment: "Operatie succesvol voltooid",
    notes: "Herstelperiode: 2 weken",
    chiefComplaint: "Sterilisatie operatie",
    createdAt: "2024-03-21T11:00:00Z",
    updatedAt: "2024-03-21T11:00:00Z",
  },
  {
    id: "3",
    patientId: "3",
    patientName: "Charlie",
    veterinarianId: "1",
    veterinarianName: "Dhr. Smit",
    type: "VACCINATIE",
    date: "2024-03-22",
    status: "ACTIEF",
    diagnosis: "Jaarlijkse vaccinatie",
    treatment: "Vaccinatie toegediend",
    notes: "Volgende vaccinatie over 1 jaar",
    chiefComplaint: "Jaarlijkse vaccinatie",
    createdAt: "2024-03-22T09:00:00Z",
    updatedAt: "2024-03-22T09:00:00Z",
  },
];
