import type { MedicalRecord, MedicalRecordStatus } from "../types";

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: "1",
    patientId: "1",
    veterinarianId: "1",
    date: "2024-03-20",
    type: "CHECK_UP",
    chiefComplaint: "Regular check-up",
    diagnosis: "Healthy",
    treatmentPlan: "Regular check-up completed",
    notes: "Patient is in good health",
    status: "ACTIVE" as MedicalRecordStatus,
    hasAttachments: false,
    followUpScheduled: false,
    followUpNotes: "",
    createdAt: "2024-03-20T10:00:00Z",
    updatedAt: "2024-03-20T10:00:00Z",
  },
  {
    id: "2",
    patientId: "2",
    veterinarianId: "1",
    date: "2024-03-20",
    type: "VACCINATION",
    chiefComplaint: "Annual vaccination due",
    diagnosis: "Due for vaccination",
    treatmentPlan: "Annual vaccination administered",
    notes: "Patient tolerated vaccination well",
    status: "RESOLVED" as MedicalRecordStatus,
    hasAttachments: false,
    followUpScheduled: true,
    followUpDate: "2025-03-20",
    followUpNotes: "Schedule next annual vaccination",
    createdAt: "2024-03-20T10:00:00Z",
    updatedAt: "2024-03-20T10:00:00Z",
  },
];
