name: Branch Protection

on:
  push:
    branches:
      - main
    paths:
      - ".github/branch-protection.yml"

jobs:
  apply-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply Branch Protection Rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');

            const config = yaml.load(fs.readFileSync('.github/branch-protection.yml', 'utf8'));
            const rules = config.branch_protection_rules;

            for (const rule of rules) {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: rule.pattern,
                required_status_checks: rule.required_status_checks,
                enforce_admins: rule.enforce_admins,
                required_pull_request_reviews: rule.required_pull_request_reviews,
                restrictions: rule.restrictions
              });
            }
