name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Run tests
        run: npm test

  branch-naming:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check branch naming convention
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF:-$GITHUB_REF#refs/heads/}
          if [[ ! $BRANCH_NAME =~ ^(feature|bugfix|hotfix|release)/[a-z0-9-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the convention: (feature|bugfix|hotfix|release)/name"
            exit 1
          fi
